Tugas 4 Pekan 3 dan Tugas 5 Pekan 3 dan Tugas 1 Pekan 4/MovieReview/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/master', function () {
    return view('layouts.master');
});

/*Route::get('profiles/create', 'ProfilesController@create');
Route::post('profiles', 'ProfilesController@store');
Route::get('profiles', 'ProfilesController@index');
Route::get('profiles/{id}', 'ProfilesController@show');
Route::get('profiles/{id}/edit', 'ProfilesController@edit');
Route::put('profiles/{id}', 'ProfilesController@update');
Route::delete('profiles/{id}', 'ProfilesController@destroy');

Route::get('casts/create', 'CastController@create');
Route::post('casts', 'CastController@store');
Route::get('casts', 'CastController@index')->name('casts.index');
Route::get('casts/{id}', 'CastController@show');
Route::get('casts/{id}/edit', 'CastController@edit');
Route::put('casts/{id}', 'CastController@update');
Route::delete('casts/{id}', 'CastController@destroy');
*/

//Route::resource('pemeran', 'PemeranController');

Route::resource('profiles', 'ProfilesController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('casts', 'CastController');

Tugas 4 Pekan 3 dan Tugas 5 Pekan 3 dan Tugas 1 Pekan 4/MovieReview/app/Cast.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cast extends Model
{
   protected $table = 'casts';
}

Tugas 4 Pekan 3 dan Tugas 5 Pekan 3 dan Tugas 1 Pekan 4/MovieReview/app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Cast;

class CastController extends Controller
{
        public function __construct() {
            $this->middleware('auth')->except(['index', 'show']);
        }
        public function create () {
            return view('pages.casts.create');
        }
        
        public function store (Request $request) {
            //dd($request->all());
            $request -> validate([
                'nama' => "required|max:45",
                'umur' => "required",
            ]);
    
            /*$query = DB::table('casts')->insert([
                'nama' => $request['nama'],
                'umur' => $request['umur'],
            ]);*/
                $cast = new Cast;
                $cast->nama = $request['nama'];
                $cast->umur = $request['umur'];
            
                $cast->save();
            
            return redirect('/casts')->with('success', 'Cast profile was created successfully!');
        }
    
        public function index() {
            //$casts = DB::table('casts')->get();
            //dd($casts->all());
            $casts = Cast::all();
            return view('pages.casts.index', compact('casts'));
        }
    
        public function show($id) {
            //$cast = DB::table('casts')->where('id', $id)->first();
            //dd($cast);
            $cast = Cast::find($id);
            return view('pages.casts.show', compact('cast'));
        }
    
        public function edit($id) {
            //$cast = DB::table('casts')->where('id', $id)->first();
            //dd($cast);
            $cast = Cast::find($id);
            return view('pages.casts.edit', compact('cast'));
        }
    
        public function update($id, Request $request) {
            $request -> validate([
                'nama' => "required|max:45",
                'umur' => "required",
            ]);
                
            $update = Cast::where('id', $id)->update([
                'nama' => $request['nama'],
                'umur' => $request['umur'],
            ]);
            /*$query = DB::table('casts')
                         ->where('id', $id)
                         ->update([
                            'nama' => $request['nama'],
                            'umur' => $request['umur'],
                         ]);*/
            
            return redirect('/casts')->with('success', 'Update saved!');
        }
    
        public function destroy($id) {
            //$query = DB::table('casts')->where('id', $id)->delete();
            $destroy = Cast::destroy($id);
             return redirect('/casts')->with('success', 'Cast profile was successfully deleted!');
        }
}

Tugas 4 Pekan 3 dan Tugas 5 Pekan 3 dan Tugas 1 Pekan 4/MovieReview/resources/views/pages/casts/create.blade.php
@extends('layouts.master')

@section('content')
        <div class="ml-3 mt-3 mr-3">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Create a Cast Profile</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="/casts" method="POST">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="inputNama">Nama</label>
                    <input type="text" class="form-control" name="nama" value="{{ old('nama', '') }}" id="inputNama" placeholder="Name">
                    @error('nama')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="inputUmur">Umur</label>
                    <input type="number" step="any" min=0 class="form-control" name="umur" value="{{ old('umur', '') }}" id="inputUmur" placeholder="Age">
                    @error('umur')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
        </div>
@endsection

Tugas 4 Pekan 3 dan Tugas 5 Pekan 3 dan Tugas 1 Pekan 4/MovieReview/resources/views/pages/casts/edit.blade.php
@extends('layouts.master')

@section('content')
        <div class="ml-3 mt-3 mr-3">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Cast Profile {{$cast->id}}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="/casts/{{$cast->id}}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="inputNama">Nama</label>
                    <input type="text" class="form-control" name="nama" value="{{ old('nama', $cast->nama) }}" id="inputNama" placeholder="Name">
                    @error('nama')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="inputUmur">Umur</label>
                    <input type="number" step="any" min=0 class="form-control" name="umur" value="{{ old('umur', $cast->umur) }}" id="inputUmur" placeholder="Age">
                    @error('umur')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Edit</button>
                </div>
              </form>
            </div>
        </div>
@endsection

Tugas 4 Pekan 3 dan Tugas 5 Pekan 3 dan Tugas 1 Pekan 4/MovieReview/resources/views/pages/casts/index.blade.php
@extends('layouts.master')

@section('content')
    <div class='ml-3 mt-3 mr-3'>
    <div class="card">
              <div class="card-header">
                <h3 class="card-title">Cast Profile Table</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                  @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                  @endif
                <div class="mb-3">
                  <a class="btn btn-outline-secondary my-2 my-sm-0" href="{{route('casts.create')}}">Create a New Cast Profile</a>
                </div>
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th style="width: 10px">#</th>
                      <th style="width: 250px">Nama</th>
                      <th style="width: 10px">Umur</th>
                      <th style="width: 110px">Link</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse($casts as $key => $cast)
                        <tr>
                            <td>{{ $key + 1 }}</td>
                            <td>{{ $cast -> nama }}</td>
                            <td>{{ $cast -> umur }}</td>
                            <td style="display: flex">
                                <a href="{{route('casts.show', ['cast' => $cast->id])}}" class="btn btn-outline-secondary btn-sm mr-1">Go</a>
                                <a href="{{route('casts.edit', ['cast' => $cast->id])}}" class="btn btn-outline-primary btn-sm mr-1">Edit</a>
                                <form action="{{route('casts.destroy', ['cast' => $cast->id])}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <input type="submit" value='Delete' class="btn btn-outline-danger btn-sm">
                                </form>
                            </td>
                        </tr>
                        @empty
                            <tr>
                                <td colspan="4" align="center">No cast profile found</td>
                            </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
              <!-- /.card-body 
              <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-right">
                  <li class="page-item"><a class="page-link" href="#">«</a></li>
                  <li class="page-item"><a class="page-link" href="#">1</a></li>
                  <li class="page-item"><a class="page-link" href="#">2</a></li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item"><a class="page-link" href="#">»</a></li>
                </ul>
              </div>
              -->
            </div>
    </div>
@endsection

Tugas 4 Pekan 3 dan Tugas 5 Pekan 3 dan Tugas 1 Pekan 4/MovieReview/resources/views/pages/casts/show.blade.php
@extends('layouts.master')

@section('content')
    <div class="mt-3 ml-3">
        <h4> {{ $cast->nama }} </h4>
        <h4> {{ $cast->umur }} </h4>
    </div>
@endsection